name: hastane_randevu_sistemi_flutter
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0
  
  shared_preferences: ^2.0.13
  table_calendar: ^3.0.0
  intl: ^0.19.0  

  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hospital_1.jpg
    - assets/images/hospital_2.jpg
    - assets/images/hospital_3.jpg
    - assets/data/doktorlar.json
    - assets/images/doktor1.jpg
    - assets/images/doktor2.jpg
    - assets/images/doktor3.jpg
    - assets/images/doktor4.jpg
    - assets/images/doktor5.jpg
    - assets/images/doktor6.jpg
    - assets/images/doktor7.jpg
    - assets/images/doktor8.jpg
    - assets/images/doktor9.jpg
    - assets/images/doktor10.jpg
